# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safeip < Formula
  desc ""
  homepage "https://github.com/darklight147/safeip"
  version "1.1.1"

  on_macos do
    url "https://github.com/darklight147/safeip/releases/download/v1.1.1/safeip_1.1.1_darwin_all.tar.gz"
    sha256 "4e965b7ed4c9b19d2a340d00b4f1f1af617454a5e05ef4c90204d60b90db49e2"

    def install
      bin.install "safeip"
      zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
      fish_completion.install "completions/goreleaser.fish"
      bash_completion.install "completions/goreleaser.bash" => "goreleaser"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darklight147/safeip/releases/download/v1.1.1/safeip_1.1.1_linux_arm64.tar.gz"
      sha256 "cc1e5d5178c54ff7d813af4849e6596b9e531816449cab590ced418b38741cd6"

      def install
        bin.install "safeip"
        zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
        fish_completion.install "completions/goreleaser.fish"
        bash_completion.install "completions/goreleaser.bash" => "goreleaser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darklight147/safeip/releases/download/v1.1.1/safeip_1.1.1_linux_amd64.tar.gz"
      sha256 "279e6efcfe1832261b13d3082fde08e98a4ad917fa959653fb4d80c9287d620c"

      def install
        bin.install "safeip"
        zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
        fish_completion.install "completions/goreleaser.fish"
        bash_completion.install "completions/goreleaser.bash" => "goreleaser"
      end
    end
  end
end
