# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safeip < Formula
  desc ""
  homepage "https://github.com/darklight147/safeip"
  version "1.1.0"

  on_macos do
    url "https://github.com/darklight147/safeip/releases/download/v1.1.0/safeip_1.1.0_darwin_all.tar.gz"
    sha256 "380a03316d179a6c99345cd0245772b2a19e73b47e7589d8c69603e9804eed21"

    def install
      bin.install "safeip"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darklight147/safeip/releases/download/v1.1.0/safeip_1.1.0_linux_arm64.tar.gz"
      sha256 "40acdc21b16198819b67f106dc952acbf318a8c6cb1dc71dba2ccdd5482460c4"

      def install
        bin.install "safeip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darklight147/safeip/releases/download/v1.1.0/safeip_1.1.0_linux_amd64.tar.gz"
      sha256 "f6f509ae8ff06e36dc8a09456c3352703274ac4dc36c5427647760ddc8796663"

      def install
        bin.install "safeip"
      end
    end
  end
end
